version: '3.1'

services:

  example:
    image: gatoke/example:1
    container_name: example-application
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/example
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example

  db:
    image: postgres:11
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres: {}